[build-system]
requires = [
  "setuptools >= 40.9.0",
  "wheel",
]

build-backend = "setuptools.build_meta"

[project]
name = "hi-clan-rank"
dynamic = ["version"]
requires-python = ">=3.12"
dependencies = [
  "requests",
  "pydantic",
  "tabulate",
]
